### ISSUE TITLE
unit 3 prep

### ISSUE THREAD

**Issue by jonasleitner** [h-varma/Team-11#7]
i just did part of the preparation stuff. (gitignore, gitattribute and requirements.txt)
for the requirements file i just checked which versions i have installed and inserted the version number.
Wouldn't it make more sense to use >= and <= instead of ==, because probably it will work with a lot more versions.

I will read a bit about that if i have more time, but maybe one of you already knows sth about that :)

**Comment by h-varma** [comment]
I didn't get around to watching the videos yet. So thanks for doing some of the tasks already. I see now that, as the repository owner, I need to prepare a user account on read the docs and publish the documentation. I will try to do that tonight.

I don't have a lot of experience with requirements files, so I'm just guessing here: I would imagine that it's easier/safer to use just == because that's the version that you have and you _know_ that it works. If you allow more versions, you would probably need to make sure that it doesn't cause problems.
